#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    entities:
        - App\Entity\Bloc
        - App\Entity\CategorieService
        - App\Entity\Image
        - App\Entity\Internaute
        - App\Entity\Position
        - App\Entity\Prestataire
        - App\Entity\Promotion
        - App\Entity\Stage