#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    site_name: 'Bien-Être'
    entities:
        - App\Entity\User
        - App\Entity\UserTemp
        - App\Entity\Provider
        - App\Entity\Client
        - App\Entity\Service
        - App\Entity\ServiceCategory
        - App\Entity\Promotion
        - App\Entity\Abuse
        - App\Entity\Comment
        - App\Entity\Image
        - App\Entity\Newsletter
        - App\Entity\Bloc
        - App\Entity\Locality
        - App\Entity\PostalCode
        - App\Entity\Township
        - App\Entity\Position


