#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
easy_admin:
    entities:
        - App\Entity\Abuse
        - App\Entity\Bloc
        - App\Entity\Client
        - App\Entity\Locality
        - App\Entity\Image
        - App\Entity\PostalCode
        - App\Entity\Position
        - App\Entity\Provider
        - App\Entity\Promotion
        - App\Entity\Stage
        - App\Entity\ServiceCategory
        - App\Entity\Township
        - App\Entity\User