framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    csrf_protection: true
    #http_method_override: true
    #trusted_hosts: ~
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    session:
        # Session native enregistré dans les fichiers de log
        # handler_id: session.handler.native_file
        # save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    # fragmenter la mise en cache d'une page via une passerelle cache
    # Permet de charger des fragments de page en cache
    # https://symfony.com/doc/current/http_cache/esi.html
    esi: { enabled: true }
    #fragments: ~
    php_errors:
        log: true

    templating:
        engines: ['twig']
#assetic:
#    debug: '%kernel.debug%'
#    use_controller: '%kernel.debug%'
#    filters:
#        cssrewrite: ~

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig'     # sliding pagination controls template
        # Autres template de pagination disponible
        #      '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        #      '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'
        #      '@KnpPaginator/Pagination/twitter_bootstrap_pagination.html.twig'
        #      '@KnpPaginator/Pagination/foundation_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template

