framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    csrf_protection: true
    #http_method_override: true
    #trusted_hosts: ~
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    session:
        # Session native enregistré dans les fichiers de log
        # handler_id: session.handler.native_file
        # save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
    # fragmenter la mise en cache d'une page via une passerelle cache
    # Permet de charger des fragments de page en cache
    # https://symfony.com/doc/current/http_cache/esi.html
    esi: { enabled: true }
    #fragments: ~
    php_errors:
        log: true

    templating:
        engines: ['twig']
#assetic:
#    debug: '%kernel.debug%'
#    use_controller: '%kernel.debug%'
#    filters:
#        cssrewrite: ~
