twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        site_name: 'ISL Symfony3.9 - Bien-Être'
        logo_url: 'build/images/favicon.png'
