# Read the documentation: https://github.com/hautelook/AliceBundle/blob/v1.4.1/README.md


nelmio_alice:
    #Configuration optionnelle
    #locale: en_US
    #seed: 1000
    #persist_once: false
    loading_limit: 30

hautelook_alice:
    fixtures_path: 'src/DataFixtures/ORM'
