<?php

namespace App\Repository;

/**
 * PromotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Pending Promotions By Provider Id
     *
     * @param int $id
     * @return array
     */
    public function findPendingByProviderId(int $id): array
    {
        $qb = $this->_em->createQueryBuilder()
            ->select("pr")
            ->from($this->_entityName, "pr")
            ->innerJoin("pr.serviceCategory","sc")
            ->addSelect("sc");

        $qb->innerJoin("pr.provider","p")
            ->addSelect("p")
            ->andWhere($qb->expr()->eq("p.id", ":id"))
            ->andWhere($qb->expr()->gte("pr.releaseDate", ":date"))
            ->setParameters(["id"=> $id, "date"=> new \DateTime()]);

        return $qb->getQuery()->getResult();
    }

    /**
     * Pending Promotions By Provider Id
     *
     * @param int $id
     * @return array
     */
    public function findOngoingByProviderId(int $id): array
    {
        $qb = $this->_em->createQueryBuilder()
            ->select("pr")
            ->from($this->_entityName, "pr")
            ->leftJoin("pr.serviceCategory","sc")
            ->addSelect("sc");

        $qb->innerJoin("pr.provider","p")
            ->addSelect("p")
            ->andWhere($qb->expr()->eq("p.id", ":id"))
            ->andWhere($qb->expr()->gte("pr.endDate", ":date"))
            ->andWhere($qb->expr()->lte("pr.startDate", ":date"))
            ->setParameters(["id" => $id, "date" => new \DateTime()]);

        return $qb->getQuery()->getResult();
    }

    /**
     * Pending Promotions By Provider Id
     *
     * @param int $id
     * @return array
     */
    public function findExpiredByProviderId(int $id): array
    {
        $qb = $this->_em->createQueryBuilder()
            ->select("pr")
            ->from($this->_entityName, "pr")
            ->leftJoin("pr.serviceCategory","sc")
            ->addSelect("sc");

        $qb->innerJoin("pr.provider","p")
            ->addSelect("p")
            ->andWhere($qb->expr()->eq("p.id", ":id"))
            ->andWhere($qb->expr()->lte("pr.expiryDate", ":date"))
            ->setParameters(["id"=> $id, "date"=> new \DateTime()]);

        return $qb->getQuery()->getResult();
    }



    /**
     * Find All Services By Provider Id
     *
     * @param int $id
     * @return array|mixed
     */
    public function findByProviderId(int $id)
    {
        $qb = $this->_em->createQueryBuilder()
            ->select("pr")
            ->from($this->_entityName, "pr")
            ->innerJoin("pr.serviceCategory","sc")
            ->addSelect("sc");

        $qb->innerJoin("pr.provider","p")
            ->addSelect("p")
            ->andWhere($qb->expr()->eq("p.id", ":id"))
            ->setParameter("id", $id);

        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */
    public function recentPromotions(): array
    {
        $queryBuilder = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p')
            ->orderBy('p.releaseDate','DESC');

        return $queryBuilder->getQuery()
            ->getResult();
    }

    public function recentPromotionsPlusProviders(): array
    {
        $queryBuilder  = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p')
            ->innerJoin("p.provider","prov")
            ->addSelect("prov")
            ->orderBy('p.releaseDate','DESC');

        return $queryBuilder->getQuery()
            ->getResult();
    }

    public function expiringPromotions(): array
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p')
            ->where('p.expiryDate > :expiryDate')
            ->setParameter('expiryDate' , date("Y-m-d H:i:s"))
            ->orderBy('p.expiryDate','ASC')
            ->setMaxResults(3);

        return $qb->getQuery()->getResult();

    }

    public function findAllByProviderId(int $id):array
    {
        $qb = $this->_em->createQueryBuilder()
            ->select("pr")
            ->from($this->_entityName, "pr")
            ->innerJoin("pr.provider","p")
            ->addSelect("p")
            ->where("p.id", ":id")
            ->setParameter("id", $id);
    }
}
