<?php

namespace App\Repository;

/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get Best Providers
     *
     * @return array
     */
    public function mostFans(){

        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName,'p')
            ->orderBy('p.totalFans','DESC')
            ->setMaxResults(4);

        return $qb->getQuery()->getResult();
    }
}
