<?php

namespace App\Repository;

use App\Entity\Provider;


/**
 * ProviderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProviderRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Join Logos
     *
     */
    protected function addLogo($qb)
    {
        $qb->innerJoin('p.logos', 'l')
        ->addSelect('l');

        return $qb;

    }


    /**
     * Get All providers + logos
     */
    public function myFindAll(): array
    {
        //Syntaxe longue
        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName, 'p')
            ->innerJoin('p.logos', 'l')
            ->addSelect('l')
            ->orderBy('p.registryDate','DESC');

        return $qb->getQuery()
            ->getResult();

    }
    /**
     * Get Best Providers
     *
     * @return array
     */
    public function mostFans(int $limit){

        $qb = $this->_em->createQueryBuilder()
            ->select('p')
            ->from($this->_entityName,'p');

        /* Utilisation de la fonction d'ajout des entités logos
            //->innerJoin('p.logos','l')
            //->addSelect('l')
        */
        $this->addLogo($qb);

        $qb->orderBy('p.totalFans','DESC')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

    /**
     * Get Recent Providers
     *
     * @return array
     */
    public function recentProviders(int $limit):array
    {
        // Syntaxe courte
        $qb = $this->createQueryBuilder('p');

        $this->addLogo($qb);

        $qb->orderBy('p.registryDate','DESC')
            ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }
}
