<?php

namespace App\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
    public function recentServices(): array
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('s')
            ->from($this->_entityName,'s')
            ->orderBy('s.releaseDate','DESC');

        return $qb->getQuery()->getResult();
    }
}

