<?php

namespace App\Repository;

/**
 * ServiceCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class ServiceCategoryRepository extends EntityRepository
{
    public function getServiceCategoriesAndProviders(int $max = 10): array
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('sc')
            ->from($this->_entityName, 'sc')
            ->innerJoin('sc.providers','p')
            ->addSelect('p')
            ->setMaxResults($max);

        return $qb->getQuery()->getResult();
    }
}
