index:
    path: /
    defaults: { _controller: 'App\Controller\HomeController::index' }

# first, run composer req annotations
# On indique des routes sont définis dans ces répertoires via des annotations
controllers:
    resource: ../src/Controller/
    type: annotation

# Routes du bundle de sécurité
security:
    resource: ../src/Security/
    type: annotation

# Routes Login & Logout
login:
    path: /login
    defaults: { _controller: 'App\Security\SecurityController::loginAction' }
logout:
    path: /logout
login_check:
    path: /login
signin:
    path: /signin
    defaults: { _controller: 'App\Security\RegistrationController::signInAction' }
