# Put parameters here that don't need to change on each machine where the app is deployed
# ATTENTION: Autowiring services based on the types they implement is deprecated since Symfony 3.3
    # and won’t be supported in version 4.0. You should rename (or alias)
    # the "security.user_password_encoder.generic" service
    # to "Symfony\Component\Security\Core\Encoder\UserPasswordEncoder" instead.
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../src/{Entity,Migrations,Repository,Tests}'

    # controllers are imported separately to make sure they
    # have the tag that allows actions to type-hint services
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    #######################################################################
    # Stockage des sessions en base de données.
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        arguments:
            - 'mysql:dbname=%env(DATABASE_NAME)%'
            - { db_table: '%env(DATABASE_SESSION_TABLE)%', db_username: '%env(DATABASE_USERNAME)%' , db_password: '%env(DATABASE_PASSWORD)%'  }

    ##########################################################################
    # Exemple :
    # Service d'envoie d'email de confirmation d'inscription
    # Installation de SwiftMailer nécessaire
    App\Email\UserMailer:
        alias: email.user_mailer
        arguments:
            - '@mailer'

    # Service écoutant l'événement postPersist pour déclencher l'action email.user_mailer
    App\DoctrineListener\UserConfirmationListener:
        alias: doctrine_listener.user_confirmation
        arguments:
            - '@email.user_mailer'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    ##########################################################################
    # Chargement des extensions Twig : ERREUR
    # Cannot autowire service "Twig\Extensions\Node\TransNode"
    #
    #Twig\Extensions\:
    #    resource: '../vendor/twig/extensions/src/*'
    #    tags:
    #      - {name : 'twig.extension'}
    #

    #########################################################################
    app.twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags: { name: 'twig.extension' }

    app.twig.extension.i18n:
        class: Twig_Extensions_Extension_I18n
        tags: { name: 'twig.extension' }
    app.twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags: { name: 'twig.extension' }

    # Syntaxe Symfony 4.0 ne fonctionne pas pour le bundle
    #
    #Twig_Extensions_Extension_Text:
    #    alias: app.twig.extension.text
    #    tags: { name: 'twig.extension' }
    ########################################################################

